quarkus:
  http:
    port: 8181
#  rest-client:
#    group-api:
#      url: http://${QUARKUS_CLIENT_HTTP:localhost}:${QUARKUS_CLIENT_PORT:8181}
  datasource:
    db-kind: postgresql
    username: ${QUARKUS_DATASOURCE_USERNAME:enlace}
    password: ${QUARKUS_DATASOURCE_PASSWORD:3nl4c3}
    jdbc:
      url: jdbc:postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5433}/group
    reactive:
      url: postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5433}/group
  micrometer:
    export:
      prometheus:
        path: /metrics

  flyway:
    migrate-at-start: true
    locations: db/migration

